export const banksUrl = [
    {url:"https://bixter.org/psicons/color/qiwi.svg",title:"QIWI",id:0, position:"ps"},
    {url:"https://bixter.org/psicons/color/bitcoin.svg",title:"Bitcoin",id:1,position:"crypto"},
    {url:"https://bixter.org/psicons/color/tethernew.svg",title:"Tether",id:2,position:"crypto"},
    {url:"https://bixter.org/psicons/color/solana.svg",title:"Solana",id:3,position:"crypto"},
    {url:"https://bixter.org/psicons/color/capitalist.svg",title:"Capitalist",id:4,position:"ps"},
    {url:"https://bixter.org/psicons/color/binance.svg",title:"Binance Coin",id:5,position:"crypto"},
    {url:"https://bixter.org/psicons/color/binanceusd.svg",title:"Binance USD",id:6,position:"crypto"},
    {url:"https://bixter.org/psicons/color/monero.svg",title:"Monero",id:7,position:"crypto"},
    {url:"https://bixter.org/psicons/color/etc.svg",title:"Ethereum Classic",id:8,position:"crypto"},
    {url:"https://bixter.org/psicons/color/visamastercard.svg",title:"Visa MasterCard",id:9,position:"bank"},
    {url:"https://bixter.org/psicons/color/ethereum.svg",title:"Ethereum",id:10,position:"crypto"},
    {url:"https://bixter.org/psicons/color/polygon.svg",title:"Polygon",id:11,position:"crypto"},
    {url:"https://bixter.org/psicons/color/perfectmoney.svg",title:"Perfect Money",id:12,position:"ps"},
    {url:"https://bixter.org/psicons/color/advcash.svg",title:"Advcash",id:13,position:"ps"},
    {url:"https://bixter.org/psicons/color/sberbank.svg",title:"Сбербанк",id:14 ,position:"bank"},
    {url:"https://bixter.org/psicons/color/tinkoff.svg",title:"Тинькофф",id:15 ,position:"bank"},
    {url:"https://bixter.org/psicons/color/litecoin.svg",title:"Litecoin",id:16,position:"crypto"},
    {url:"https://bixter.org/psicons/color/payeer.svg",title:"Payeer",id:17,position:"ps"},
    {url:"https://bixter.org/psicons/color/tron.svg",title:"TRON",id:18,position:"crypto"},
    {url:"https://bixter.org/psicons/color/stellar.svg",title:"Stellar",id:19,position:"crypto"},
    {url:"https://bixter.org/psicons/color/usdcoin.svg",title:"USD Coin",id:20,position:"crypto"},
    {url:"https://bixter.org/psicons/color/dash.svg",title:"Dash",id:21,position:"crypto"},
    {url:"https://bixter.org/psicons/color/ripple.svg",title:"Ripple",id:22,position:"crypto"},
    {url:"https://bixter.org/psicons/color/bitcoincash.svg",title:"Bitcoin Cash",id:23,position:"crypto"},
    {url:"https://bixter.org/psicons/color/tezos.svg",title:"Tezos",id:24,position:"crypto"},
    {url:"https://bixter.org/psicons/color/raiffeisen.svg",title:"Райффайзенбанк",id:25,position:"bank"},
    {url:"https://bixter.org/psicons/color/cosmos.svg",title:"Cosmos",id:26,position:"crypto"},
    {url:"https://bixter.org/psicons/color/alfabank.svg",title:"Альфабанк",id:27 ,position:"bank"},
    {url:"https://bixter.org/psicons/color/dogecoin.svg",title:"Dogecoin",id:28,position:"crypto"},
    {url:"https://bixter.org/psicons/color/shibainu.svg",title:"Shiba Inu",id:29,position:"crypto"},
    {url:"https://bixter.org/psicons/color/eos.svg",title:"EOS",id:30,position:"crypto"},
    {url:"https://bixter.org/psicons/color/open.svg",title:"Открытие",id:31,position:"bank"},
    {url:"https://bixter.org/psicons/color/perfectmoneyvoucher.svg",title:"PM e-Voucher",id:32,position:"bank"},
    {url:"https://bixter.org/psicons/color/algorand.svg",title:"Algorand",id:33,position:"crypto"},
    {url:"https://bixter.org/psicons/color/avalanche.svg",title:"Avalanche",id:34,position:"bank"},
    {url:"https://bixter.org/psicons/color/dai.svg",title:"Dai",id:35,position:"crypto"},
    {url:"https://bixter.org/psicons/color/polkadot.svg",title:"Polkadot",id:36,position:"crypto"},
    {url:"https://bixter.org/psicons/color/homecredit.svg",title:"Хоум Кредит",id:37,position:"bank"},
    {url:"https://bixter.org/psicons/color/zcash.svg",title:"Zcash",id:38,position:"crypto"},
    {url:"https://bixter.org/psicons/color/cardano.svg",title:"Cardano",id:39,position:"crypto"},
    {url:"https://bixter.org/psicons/color/decentraland.svg",title:"Decentraland",id:40,position:"crypto"},
    {url:"https://bixter.org/psicons/color/uniswap.svg",title:"Uniswap",id:41,position:"crypto"},
    {url:"https://bixter.org/psicons/color/halykbank.svg",title:"Halyk Bank",id:42,position:"bank"},
    {url:"https://bixter.org/psicons/color/fortebank.svg",title:"ForteBank",id:43,position:"bank"},
    {url:"https://bixter.org/psicons/color/jysanbank.svg",title:"Jysan Bank",id:44,position:"bank"},
    {url:"https://bixter.org/psicons/color/kaspibank.svg",title:"Kaspi Bank",id:45,position:"bank"},
    {url:"https://bixter.org/psicons/color/vtb.svg",title:"ВТБ",id:46,position:"bank"},
    {url:"https://bixter.org/psicons/color/mir.svg",title:"Мир",id:47,position:"bank"},
    {url:"https://bixter.org/psicons/color/rosbank.svg",title:"РосБанк",id:48,position:"bank"},
    {url:"https://bixter.org/psicons/color/pochtabank.svg",title:"ПочтаБанк",id:49,position:"bank"},
    {url:"https://bixter.org/psicons/color/rshb.svg",title:"Россельхозбанк",id:50,position:"bank"},
    {url:"https://bixter.org/psicons/color/gazprombank.svg",title:"Газпромбанк",id:51,position:"bank"},
    {url:"https://bixter.org/psicons/color/psbank.svg",title:"Промсвязьбанк",id:52,position:"bank"},
    {url:"https://bixter.org/psicons/color/mtsbank.svg",title:"МТС Банк",id:53,position:"bank"},
    {url:"https://bixter.org/psicons/color/rncb.svg",title:"РНКБ",id:54,position:"bank"},
    {url:"https://bixter.org/psicons/color/russtandart.svg",title:"Русский стандарт",id:55,position:"bank"},
    {url:"https://bixter.org/psicons/color/avangard.svg",title:"Авангард",id:56,position:"bank"}
]
